#!/bin/bash

DCL=$1

if [ $1 = all ]
then
	for dir in `ls "$DISCODE_DCL_DIR"`
	do
		if [ -d "$DISCODE_DCL_DIR/$dir/build" ]; then
			echo -en "\e[1;33m"
			echo "================================================="
			echo ">>> [ $dir ]"
			echo "================================================="
			echo -en '\e[00m'
			make -C $DISCODE_DCL_DIR/$dir/build --no-print-directory install
		fi
	done
else
	shift
	make -C $DISCODE_DCL_DIR/$DCL/build --no-print-directory $@
fi

